name: Deploy

on:
  push:
    branches: [feature/github]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

# permissions:
#   contents: read

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Build SPA
        uses: ./.github/actions/build-spa
        with:
          node-version: 24
          artifact-name: dist

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from GitHub
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Upload artifact to AWS S3 bucket
        run: aws s3 sync dist/ng-virtual-scroll/browser s3://ng-virtual-scroll-bucket/ --delete
